# Generated by Django 3.2.7 on 2021-10-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgames',
            name='boardgames_year',
            field=models.IntegerField(default='2021'),
        ),
        migrations.AlterField(
            model_name='boardgames',
            name='boardgames_genre',
            field=models.CharField(max_length=50),
        ),
    ]
