# Generated by Django 3.2.7 on 2021-11-16 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20211116_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardgamesavailable',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='boardgamesrequested',
            old_name='user_name',
            new_name='username',
        ),
    ]
