# Generated by Django 3.2.9 on 2021-12-02 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20211116_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgamesavailable',
            name='boardgames',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.boardgames'),
            preserve_default=False,
        ),
    ]
