# Generated by Django 3.2.9 on 2021-12-02 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_boardgamesavailable_boardgames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgamesavailable',
            name='boardgames_title',
        ),
        migrations.RemoveField(
            model_name='boardgamesrequested',
            name='boardgames_title',
        ),
        migrations.AddField(
            model_name='boardgamesrequested',
            name='boardgames',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.boardgames'),
            preserve_default=False,
        ),
    ]
